### ISSUE TITLE
UDP Connection Refused - UDP_-_EDNS0_4096_D_KN

### ISSUE THREAD

**Issue by XyjpcpXNF6UGaQ** [dnsviz/dnsviz#106]
Having a few issues trying to get visual validation on IPv6 for corequery.uk:

corequery.uk zone: The server(s) were not responsive to queries over UDP. (2a00:b900:10df::2, 2a00:b900:10df::4)
corequery.uk/A: The UDP connection was refused (ECONNREFUSED). (2a00:b900:10df::2, 2a00:b900:10df::4, UDP_-_EDNS0_4096_D_KN)
corequery.uk/NS: The UDP connection was refused (ECONNREFUSED). (2a00:b900:10df::2, 2a00:b900:10df::4, UDP_-_EDNS0_4096_D_KN)

[https://dnsviz.net/d/corequery.uk/dnssec/](url)

I do not consider this to be a problem because everything else validates, including the IPv6 of a related domain that depends on corequery.uk for its nameservers; but I would be interested to know whether this problem could be due to the response from my webserver exceeding the allowed packet size for UDP due to key size being 4096 bits, with a double-key DNSSEC arrangement?

I can confirm that ICMP is working on the server, and PING requests work as expected. Additionally, there are no load-balancers and no UDP blocking ISP, router, or firewall level. Dig gives the following on AAAA lookup:

##
[alt@default-46-33-152-198 ~]# dig -t aaaa corequery.uk.

; <<>> DiG 9.16.33-RH <<>> -t aaaa corequery.uk.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57103
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 2, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;corequery.uk.                  IN      AAAA

;; ANSWER SECTION:
corequery.uk.           82980   IN      AAAA    2a00:b900:10df::2
corequery.uk.           82980   IN      AAAA    2a00:b900:10df::4

;; AUTHORITY SECTION:
corequery.uk.           82533   IN      NS      ns2.corequery.uk.
corequery.uk.           82533   IN      NS      ns1.corequery.uk.

;; ADDITIONAL SECTION:
ns1.corequery.uk.       81402   IN      A       46.33.151.226
ns1.corequery.uk.       81402   IN      AAAA    2a00:b900:10df::2
ns2.corequery.uk.       81402   IN      A       46.33.151.228
ns2.corequery.uk.       81402   IN      AAAA    2a00:b900:10df::4

;; Query time: 19 msec
;; SERVER: 46.33.128.50#53(46.33.128.50)
;; WHEN: Sun Oct 02 07:34:19 BST 2022
;; MSG SIZE  rcvd: 221
##

##
[alt@default-46-33-152-198 ~]# dig corequery.uk. +dnssec +multi

; <<>> DiG 9.16.33-RH <<>> corequery.uk. +dnssec +multi
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38922
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 3, ADDITIONAL: 9

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;corequery.uk.          IN A

;; ANSWER SECTION:
corequery.uk.           82429 IN A 46.33.151.226
corequery.uk.           82429 IN A 46.33.151.228
corequery.uk.           82429 IN RRSIG A 13 2 86400 (
                                20221029012612 20221001040723 6400 corequery.uk.
                                r2BD9vRNh+qpGDPAgAFMu8nCICkRSYo7qLcv/wBZW2id
                                bnvXuAU632RuEtouk+HbVMn7TYEjR6FF/wyBh3/dfA== )

;; AUTHORITY SECTION:
corequery.uk.           82429 IN NS ns1.corequery.uk.
corequery.uk.           82429 IN NS ns2.corequery.uk.
corequery.uk.           82876 IN RRSIG NS 13 2 86400 (
                                20221029012612 20221001040723 6400 corequery.uk.
                                6A4D0LJzBTlTBVLxfEg+Qrg/U9WYR4FBW/ATOIX4SYva
                                F3H+22z+pwZK606dVOUAW9+zkwCjqlIzaVlIi9BC+g== )

;; ADDITIONAL SECTION:
ns1.corequery.uk.       81298 IN A 46.33.151.226
ns1.corequery.uk.       81298 IN AAAA 2a00:b900:10df::2
ns2.corequery.uk.       81298 IN A 46.33.151.228
ns2.corequery.uk.       81298 IN AAAA 2a00:b900:10df::4
ns1.corequery.uk.       82876 IN RRSIG A 13 3 86400 (
                                20221017033405 20221001040723 6400 corequery.uk.
                                SrXU/vp7pbzt1CJh88q2X3Q4UARDYiyE1sUxdVqHOGXQ
                                llESOC7zadwD1YIaWvw6dFWwAF4/n1h4wBcyEXseSQ== )
ns1.corequery.uk.       82876 IN RRSIG AAAA 13 3 86400 (
                                20221017033405 20221001040723 6400 corequery.uk.
                                GzK04C5nZXrn9A6KR/lMt7Ar7cP4cRDF9yQuixwhIsTG
                                +OYjqpDX0wtTBAGAPRJdsQK7s1YN0KPMJKTY87+azA== )
ns2.corequery.uk.       82876 IN RRSIG A 13 3 86400 (
                                20221015152916 20221001040723 6400 corequery.uk.
                                Daci7gzSPELIfn/w2+1pFpb0kdOcnJ8s/xktrtmiJ9MY
                                I+CaCM718dR+AHDt2wvIjPo9pyPpMbRUvbBB1tMgkA== )
ns2.corequery.uk.       82876 IN RRSIG AAAA 13 3 86400 (
                                20221015152916 20221001040723 6400 corequery.uk.
                                9g+oxcR63DbpZyJaJpn4/eq0Bi9GiDKKkUriieG09+zp
                                WItHUWKso76XIIAlPl+FONAEfcbxw7dpTsElsp9xaQ== )

;; Query time: 19 msec
;; SERVER: 46.33.128.50#53(46.33.128.50)
;; WHEN: Sun Oct 02 07:36:03 BST 2022
;; MSG SIZE  rcvd: 845
##

Distro: Fedora 36
DNS:    BIND 9.16.33-RH (Extended Support Version)

**Comment by cdeccio** [comment]
Hi, sorry for the belated response.   First, I cannot reproduce this at the moment, perhaps because the issue is over two months old, and the configuration or environment might have changed since then.  All queries to the corequery.uk servers are timing out.  Nonetheless, I can tell you that ECONNREFUSED means that DNSViz queries are getting ICMP port unreachable responses.  That tells me that the issue was either that the DNS server was not listening or that a firewall was rejecting requests.  In either case, the queries were (apparently) never making it to the application.
