### ISSUE TITLE
Weird warnings: 'Validation of DNSSEC algorithm 8 (RSASHA256) is not supported by this code'

### ISSUE THREAD

**Issue by mdavids** [dnsviz/dnsviz#108]
Example:

https://dnsviz.net/d/example.nl/dnssec/?rr=all&a=all&ds=all&doe=on&ta=.&tk=

This is with the 'denial of existence'-option enabled.

**Comment by cdeccio** [comment]
Fixed [here](https://github.com/dnsviz/dnsvizwww/commit/57c98b8783dbc487e0de1e526a31ba749336bb54).  Thanks!

(Hasn't been pushed to https://dnsviz.net/ just yet though...)
