### ISSUE TITLE
HTTP 500 error when having some invalid configuration

### ISSUE THREAD

**Issue by ben221199** [dnsviz/dnsviz#110]
Hello there,

At the moment I'm implementing DNSSEC in my own written Java DNS server.
However, when I test if I'm implementing correct, I sometimes get a 500 error: https://dnsviz.net/d/yocto.eu/Y6oT3g/dnssec/.
I cannot look into the logs, so I hope that somebody authorized can share more information about it.

As far as I know the RRSIG and DNSKEY kan both have incorrect information, but if a broken RRSIG points to a broken DNSKEY using the Key Tag, then the error occurs.

Hope somebody can help.

Thanks in advance

**Comment by cdeccio** [comment]
Hi Ben, for some reason I'm not getting the log message, but I can confirm the error.  Maybe pull down the DNSViz code yourself (i.e., from this repo) and run `dnsviz query yocto.eu | dnsviz print` to see what you can track down.

**Comment by ben221199** [comment]
When executing `dnsviz query yocto.eu | dnsviz print`, I got:
> There was an error parsing the JSON input: "0"

**Comment by cdeccio** [comment]
> When executing `dnsviz query yocto.eu | dnsviz print`, I got:
> 
> > There was an error parsing the JSON input: "0"

Oops, should be `dnsviz probe yocto.eu | dnsviz print`.

Anyway, the issue (fixed in 007d6dd) is that your fake key has inconsistent values, the exponent length in particular, for which DNSViz wasn't checking, and it simply crashed.  I've added some checks.

**Comment by ben221199** [comment]
That command just shows me some information. It doesn't throw any 500, because it isn't HTTP.

**Comment by cdeccio** [comment]
You're right.  The fix hasn't been applied to the HTTP server yet.  I provided you the command-line version to try to reproduce it locally since the server wasn't providing the information.

**Comment by ben221199** [comment]
I also see the project DNSVizWWW. Is that the HTTP frontend of DNSViz? I saw it wasn't Dockerized.

**Comment by cdeccio** [comment]
Yeah, that is the base for https://dnsviz.net/, but it's not really an off-the-shelf thing 😄.  I mean if an individual can get it work, that's great, but it has never really received the attention that it would need for "releases", etc.  It really is just a place to keep the code for the Web site.

**Comment by ben221199** [comment]
Ok. I hope DNSViz will work again soon, wherever this bug may be.
