### ISSUE TITLE
hidden error when showing all types

### ISSUE THREAD

**Issue by vcunat** [dnsviz/dnsviz#116]
I just ran into a case where no error is shown by default (all RR types):
https://dnsviz.net/d/moneta.cz/Y8k1MQ/dnssec/
(just warnings; even if I check DoE)

But when I select the broken RR type, it will get shown:
https://dnsviz.net/d/moneta.cz/Y8k1MQ/dnssec/?rr=28&a=all&ds=all&ta=.&tk=

**Comment by cdeccio** [comment]
Thanks.  This is related to (but not the same as) #76 .  I'm finally starting to make my way through some of the issues that have been piling up, so hopefully I'll get to this one soon.

**Comment by cdeccio** [comment]
Also, technically these are issues for dnsvizwww, not dnsviz, but it's okay to have them here for now.

**Comment by vcunat** [comment]
Oh, I haven't even realized that there are two repos.  Thanks.

**Comment by cdeccio** [comment]
I wouldn't really expect you to.  The other one exists but is more for me than for anyone else.  It isn't what I would call "easily installable".  Anyway, like I said, having the issue/request here is just fine, it just so happens that the code that needs to be fixed is over there.

**Comment by cdeccio** [comment]
Fixed with https://github.com/dnsviz/dnsvizwww/commit/cf8820c9448278a36693a012ab5b5f47a0096981. Will be deployed to Web site soon.
