### ISSUE TITLE
Missing symlink

### ISSUE THREAD

**Issue by multiflexi** [dnsviz/dnsviz#117]
On Ubuntu 22.04.1 there is necessary to create a symlink:
`ln -s  /usr/local/share/dnsviz /usr/share/dnsviz`

**Comment by cdeccio** [comment]
Could you describe how the package was installed?

**Comment by multiflexi** [comment]
Sure. I installed dependencies from distro repo and then the dnsviz with pip systemwide.

**Comment by cdeccio** [comment]
The recommended way to install dnsviz on ubuntu is with `apt` and secondarily with `pip` in a virtual environment.  Because it's already so complicated to get the paths right, and because there is a recommended way to do this, I'm going to leave this one alone.  Thanks.
