### ISSUE TITLE
0.10.0 release is not tagged and missing on https://github.com/dnsviz/dnsviz/releases

### ISSUE THREAD

**Issue by Flowdalic** [dnsviz/dnsviz#122]
It seems that 0.10.0 was released recently, however this release is not tagged and not listed on https://github.com/dnsviz/dnsviz/releases.

**Comment by cdeccio** [comment]
There were a few other things needing attention when I accidentally created the tag.  I guess I should just skip 0.10 and go to 0.11 at this point, so I don't mess things up?

**Comment by cdeccio** [comment]
I just released 0.10.0.  https://github.com/dnsviz/dnsviz/releases/tag/v0.10.0
