### ISSUE TITLE
gpg key expired

### ISSUE THREAD

**Issue by SvenVD-be** [dnsviz/dnsviz#125]
FYI:

gpg --verify dnsviz-0.9.4.tar.gz.asc dnsviz-0.9.4.tar.gz
gpg: Signature made di 28 sep 05:51:32 2021 CEST
gpg:                using RSA key 048D0B43891D7E7BCCAAEF011ED2ED92118571E6
gpg: Good signature from "Casey Deccio <casey@deccio.net>" [expired]
gpg:                 aka "Casey Deccio <casey@byu.net>" [expired]
gpg:                 aka "Casey Deccio <casey@byu.edu>" [expired]
gpg: Note: This key has expired!

Maybe it should be extended

thanks

**Comment by cdeccio** [comment]
Hopefully better now?
