### ISSUE TITLE
pip installing into a python 3 environment throws error

### ISSUE THREAD

**Issue by derekargueta** [dnsviz/dnsviz#13]
![image](https://cloud.githubusercontent.com/assets/5253821/22010376/0e19a24e-dc46-11e6-9764-e431725b4be7.png)

I can't find the offending line in the source so perhaps Pypi needs to be updated?

python version: 3.6.0
pip version: 9.0.1
virtualenv version: 15.0.3

Additionally tried the `--no-cache-dir` option with pip in case it was a cached bad build from building the source earlier, but same result.

**Comment by cdeccio** [comment]
Fixed in 1b324de369085dc4871173c414a521a7a7dc42bf, but I haven't drafted a new release with that fix.  Note that there are other python3 compatibility issues with that release, which have also been fixed since.
