### ISSUE TITLE
M2crypto backend should be replaced with cryptography module

### ISSUE THREAD

**Issue by pemensik** [dnsviz/dnsviz#138]
The first article in repository https://gitlab.com/m2crypto/m2crypto says m2crypto is in maintenance mode and should not be used. It would be great if ``cryptography`` module were used instead.

Recent python 3.13 had issues with m2crypto and it took long time to fix it. Ideally crypto parts should be rewritten using cryptography. Which is recommended by m2crypto maintainer anyway. But replacing m2crypto would not be small task and needs to be done carefully.

Anyway, dnsviz is one of few packages on Fedora, which still depends on m2crypto. To avoid problems with upcoming python versions, we should switch to more actively maintained crypto module.

- https://packages.fedoraproject.org/pkgs/dnsviz/dnsviz/fedora-rawhide.html#dependencies

**Comment by pemensik** [comment]
Last bug connected to m2crypto:
- https://bugzilla.redhat.com/show_bug.cgi?id=2291510

**Comment by cdeccio** [comment]
Thanks for the heads up.  [Here is a start](https://github.com/dnsviz/dnsviz/tree/replace-m2crypto-with-cryptography).

**Comment by cdeccio** [comment]
Please see #140.  It has been tested quite a bit on multiple versions of Debian and with multiple versions of cryptography, but could use some additional testing on other platforms.

**Comment by cdeccio** [comment]
(And also, why didn't I learn about this sooner??) 🤯

**Comment by cdeccio** [comment]
Fixed with #140 .

**Comment by cdeccio** [comment]
Fixed with #140.
