### ISSUE TITLE
Incorrect reporting of ORIGINAL_TTL_EXCEEDED_RRSET

### ISSUE THREAD

**Issue by fcelda** [dnsviz/dnsviz#139]
DNSViz reports the ORIGINAL_TTL_EXCEEDED_RRSET error if two authoritative servers return identical answers but a different TTL.

I'm attaching output of `dnsviz probe --authoritative-analysis --ancestor . edgeapi.slack.com. -x edgeapi.slack.com:dns1.p01.nsone.net,ns01.slackdns.com`: [edgeapi_slack_com.probe.gz](https://github.com/user-attachments/files/16126490/edgeapi_slack_com.probe.gz)

Here is the snippet of dnsviz print with the errors:

```
$ dnsviz print < edgeapi_slack_com.probe
...
edgeapi.slack.com [.] [.]
...
  [.]  A: 3.67.35.217, 3.67.131.16
  [.]    RRSIG: edgeapi.slack.com/13/12196 (2024-07-07 - 2024-07-09) [.!]
           E:ORIGINAL_TTL_EXCEEDED_RRSET
  [.]    RRSIG: edgeapi.slack.com/13/12196 (2024-07-07 - 2024-07-09) [.!]
           E:ORIGINAL_TTL_EXCEEDED_RRSET
  [.]    RRSIG: edgeapi.slack.com/13/49353 (2024-07-07 - 2024-07-09) [.]
...
```

Here are the individual responses and the TTLs extracted from dnsviz grok with a jq sorcery: 

```
$ dnsviz grok < /tmp/edgeapi_slack_com.probe | jq '."edgeapi.slack.com.".queries."edgeapi.slack.com./IN/A".answer.[] | {id:.id, ns_names:.ns_names, rdata:.rdata, ttl:.ttl, rrsig:[ .rrsig[] | {status:.status, ttl:.ttl, original_ttl:.original_ttl} ]} '
{
  "id": "edgeapi.slack.com./IN/A",
  "ns_names": [
    "ns01.slackdns.com."
  ],
  "rdata": [
    "3.67.35.217",
    "3.67.131.16"
  ],
  "ttl": 279,
  "rrsig": [
    {
      "status": "VALID",
      "ttl": 279,
      "original_ttl": 279
    }
  ]
}
{
  "id": "edgeapi.slack.com./IN/A",
  "ns_names": [
    "dns1.p01.nsone.net."
  ],
  "rdata": [
    "3.67.35.217",
    "3.67.131.16"
  ],
  "ttl": 166,
  "rrsig": [
    {
      "status": "VALID",
      "ttl": 166,
      "original_ttl": 166
    },
    {
      "status": "VALID",
      "ttl": 166,
      "original_ttl": 166
    }
  ]
}
```

I think dnsviz shouldn't be checking RRSIGs from one answer against data RR sets in another answer. In this particular case, the A records were generated on-the-fly from an ALIAS record by the authoritative server and the server used the TTL from the resolved ALIAS target.

Note that this is reproducible with dnsviz from the master branch. I cannot reproduce with dnsviz 0.9.4 packaged for Fedora 40.
 
It also seems to be specific to dnsviz print (and maybe graph) because dnsviz grok is not registering the error.

**Comment by cdeccio** [comment]
Hmm.  I thought I knew what was going on (and thought I had a fix...) until I realized that you were running `dnsviz probe` with the `--authoritative-analysis` option (as opposed to a recursive analysis).  Will need to look a little closer at this...

**Comment by fcelda** [comment]
I can confirm this is fixed. Thank you @cdeccio!
