### ISSUE TITLE
Problem with verification on a domain

### ISSUE THREAD

**Issue by mitchellkrogza** [dnsviz/dnsviz#14]
Hi folks, thanks for the great tool which is such an essential tool for me.

I seem to have a problem with a new domain I purchased photographer.hosting.
I first of all had problems trying to add the DS keys at GoDaddy for 2 weeks due to a timeout between GoDaddy and the .hosting registry.

I eventually managed to add the DS keys today and within a few minutes http://dnssec-debugger.verisignlabs.com/photographer.hosting picked it up and flagged everything as OK.

Yet http://dnsviz.net/d/photographer.hosting/dnssec/ is still showing me errors and I've been trying throughout the day by forcing DNSVIZ to update.

Is this a problem with the .hosting registry itself or perhaps that DNSVIZ is not seeing the update DNS records yet?

**Comment by cdeccio** [comment]
> On Jan 28, 2017, at 8:59 AM, Mitchell Krog <notifications@github.com> wrote:
> 
> Hi folks, thanks for the great tool which is such an essential tool for me.
> 
> I seem to have a problem with a new domain I purchased photographer.hosting.
> I first of all had problems trying to add the DS keys at GoDaddy for 2 weeks due to a timeout between GoDaddy and the .hosting registry.
> 
> I eventually managed to add the DS keys today and within a few minutes http://dnssec-debugger.verisignlabs.com/photographer.hosting <http://dnssec-debugger.verisignlabs.com/photographer.hosting> picked it up and flagged everything as OK.
> 
> Yet http://dnsviz.net/d/photographer.hosting/dnssec/ <http://dnsviz.net/d/photographer.hosting/dnssec/> is still showing me errors and I've been trying throughout the day by forcing DNSVIZ to update.
> 

The errors are:

"hosting zone: The server(s) were not responsive to queries over UDP. (64.96.245.53)"
". to hosting: The following NS name(s) were found in the authoritative NS RRset, but not in the delegation NS RRset (i.e., in the . zone): ns2.uniregistry.info"

Neither of these have to do with your domain; they are both problems with .hosting.  And they are related.  .hosting has a spurious NS record in the child zone that's not in the parent.  The server doesn't respond to queries.  It was probably intended to have been removed along with the corresponding record in the parent.

If I were you, I would contact .hosting, forward them the above message, and send them this:

http://dnsviz.net/d/hosting/WIynEw/dnssec/

Thanks,
Casey

**Comment by mitchellkrogza** [comment]
Thanks Casey, have reported it to them, hope they will sort it out. Will let you know what I hear back.

**Comment by mitchellkrogza** [comment]
Just an update, I did email Uniregistry but got no reply. It appears they have fixed the one error now allowing queries over UDP but there is still one error remaining as per a fresh lookup this morning.

**. to hosting: The following NS name(s) were found in the authoritative NS RRset, but not in the delegation NS RRset (i.e., in the . zone): ns2.uniregistry.info**

**Comment by mitchellkrogza** [comment]
Does anyone have any ability to contact Uniregistry and get this fixed? It's over 2 months now, they ignored my email and this error on .hosting persists.

`. to hosting: The following NS name(s) were found in the authoritative NS RRset, but not in the delegation NS RRset (i.e., in the . zone): ns2.uniregistry.info`
