### ISSUE TITLE
[Feature]: implement `dnsviz version`

### ISSUE THREAD

**Issue by andreasschulze** [dnsviz/dnsviz#143]
a version information is (if I didn't miss something) only visible on github.com or somewhere deep inside a file PKG-INFO

it would by nice if I could simply call `dnsviz version`

**Comment by cdeccio** [comment]
@andreasschulze Does this work?

**Comment by andreasschulze** [comment]
perfect, and amazing fast. Thanks a lot

```
root@2bfe8d899440:/# dnsviz -v
0.11.0
```

**Comment by cdeccio** [comment]
Fortunately that one was easy 😅
