### ISSUE TITLE
DNSViz sometimes hex-encodes NSID values

### ISSUE THREAD

**Issue by mnordhoff** [dnsviz/dnsviz#147]
Currently, if you have an NSID value like `example`, https://dnsviz.net/ sometimes displays it as e.g. `0x6578616d706c65`.

E.g. on https://dnsviz.net/d/dns-oarc.net/Zs4AeA/dnssec/ right now, the NSIDs are displayed normally down to the `net` zone `DNSKEY`, but starting with the `dns-oarc.net` `DS`, they're all hex-encoded.

There were recent changes to NSID handling in #134.

A couple weeks ago, I think the text NSID values were sometimes `"quoted"` instead.

On 2024-08-20, I thought the issue had gone away, but apparently not.

(I swear the hex characters used to be uppercase, too, but I'm probably mistaken.)

**Comment by cdeccio** [comment]
Apparently `all()` is different in python2 vs. python3:

```
$ python
Python 2.7.16 (default, Mar 23 2024, 18:55:36) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> s = b'\x61\x64\x6d\x30\x31\x2e\x73\x6a\x63\x2e\x64\x6e\x73\x2d\x6f\x61\x72\x63\x2e\x6e\x65\x74'
>>> all(c >= 0x20 and c <= 0x7e for c in s)
False
```

vs.

```
$ python3
Python 3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> s = b'\x61\x64\x6d\x30\x31\x2e\x73\x6a\x63\x2e\x64\x6e\x73\x2d\x6f\x61\x72\x63\x2e\x6e\x65\x74'
>>> all(c >= 0x20 and c <= 0x7e for c in s)
True 
```

Yes, dnsviz.net is still running on python2 🥴

**Comment by cdeccio** [comment]
Will have to see what I can do...

**Comment by mnordhoff** [comment]
Thank you! :-) Verified fixed, at least for the zones I checked.
