### ISSUE TITLE
Incorrect warning

### ISSUE THREAD

**Issue by patch-work** [dnsviz/dnsviz#154]
The following warning appears for ED25519 signed keys:

> RRSIG example.org/DS alg 10, id 18395: DNSSEC implementers are recommended against implementing signing with DNSSEC algorithm 10 (RSASHA512). See RFC 8624, Sec. 3.1.

**Comment by cdeccio** [comment]
Thanks. I would need a reproducible example to figure out how to fix this.

**Comment by patch-work** [comment]
The domain itself "example.tld." is signed using ED25519. However, "tld." is signed using RSASHA512, hence the domain is presented with the above warning. It is ok to warn the user.
