### ISSUE TITLE
./DNSKEY: No response was received from the server over UDP

### ISSUE THREAD

**Issue by hsntgm** [dnsviz/dnsviz#19]
Hello,

I get following errors; I could not manage the solve what cause this errors. 

./DNSKEY: No response was received from the server over UDP (tried 12 times). (192.36.148.17, UDP_0_EDNS0_32768_57)

./DNSKEY: No response was received from the server over UDP (tried 4 times). (192.36.148.17, UDP_0_EDNS0_32768_512)

com/DS (alg 8, id 30909): No response was received until the UDP payload size was decreased, indicating that the server might be attempting to send a payload that exceeds the path maximum transmission unit (PMTU) size. (192.36.148.17, UDP_0_EDNS0_32768_4096)

com/DS (alg 8, id 30909): No response was received until the UDP payload size was decreased, indicating that the server might be attempting to send a payload that exceeds the path maximum transmission unit (PMTU) size. (192.36.148.17, UDP_0_EDNS0_32768_4096)

```
root@server:~# dig @127.0.0.1 +short rs.dns-oarc.net txt
rst.x490.rs.dns-oarc.net.
rst.x461.x490.rs.dns-oarc.net.
rst.x466.x461.x490.rs.dns-oarc.net.
"Tested at 2017-03-08 19:19:02 UTC"
"139.162.146.144 sent EDNS buffer size 512"
"139.162.146.144 DNS reply size limit is at least 490"
root@server:~#
```

```
root@server:~# dig +short rs.dns-oarc.net txt
rst.x4090.rs.dns-oarc.net.
rst.x4058.x4090.rs.dns-oarc.net.
rst.x4064.x4058.x4090.rs.dns-oarc.net.
"139.162.130.22 DNS reply size limit is at least 4090"
"139.162.130.22 sent EDNS buffer size 4096"
"Tested at 2017-03-08 19:20:26 UTC"
root@server:~#
```
Sincerely,

**Comment by cdeccio** [comment]
There is a problem reaching i.root-servers.net due to routing issues in the LACNIC area.  We're aware of the problem, but it's out of our hands.  Others are working it.  Thanks.

**Comment by hsntgm** [comment]
I didn't expect such a hard problem ,this is also over my knowledge. Does it depend to domain registrar? 

For example if i buy a domain from x company my domain root server will assigned to a.root-servers.net and  i prefer to y company it will assign j.root-servers.net.

Thanks,

**Comment by cdeccio** [comment]
No, this is out of your control completely, no matter who your registrar is.  You don't get to pick which root servers are used by resolvers--a resolver could use any of them.  In any case, resolvers can work around this by simply picking another server to query, so as long as one is reachable, it will work, even if it's slow.

**Comment by hsntgm** [comment]
This helped me really thank you @cdeccio ..

If i understand correctly all this root.servers works like a load balancer and they are connected to each other. One more thing, are these root server operators for example verisign authorized to redirect these dns queries according to country flags for example resolver is in x counrty able to use fastest root.server while y county is not.

Thanks,
