### ISSUE TITLE
CAA record support

### ISSUE THREAD

**Issue by osirisinferi** [dnsviz/dnsviz#20]
Hi there,

Recently, [Ballot 125](https://cabforum.org/2014/10/14/ballot-125-caa-records/) of the CA/Browser Forum was passed, which means every CA will need to check for CAA records somewhere in the future.

Some CA's do this already, like Let's Encrypt. Unfortunately, [some users have troubles regarding CAA records](https://cabforum.org/2014/10/14/ballot-125-caa-records/).

The [dnsviz site](https://dnsviz.net), which is build upon this software, is a very helpful tool for this, as many times DNSSEC errors or other troublesome circumstances are the reason for this.

Unfortunately, at the moment it isn't possible to explicit select CAA records on the site (the "Advanced" methods of the site [has helped me in the past](https://community.letsencrypt.org/t/dns-01-invalid-challenge/28542/7)) and as far as I could tell from the source code of this repo, there isn't CAA record support yet.

The CAA record was [added to dnspython in version 1.13.0](https://github.com/rthalley/dnspython/compare/v1.12.0...v1.13.0).

Therefore my request to add CAA record support :slightly_smiling_face: 

Related issue for the `dnsviz` site: https://github.com/dnsviz/dnsvizwww/issues/2

**Comment by cdeccio** [comment]
This support is already supported in the DNSViz library and command line suite of tools--assuming the version of dnspython is sufficient.

Support for dnsviz/dnsvizwww and http://dnsviz.net/ has been added in response to dnsviz/dnsvizwww#2 .

**Comment by Night1** [comment]
Hey, CAA tests it not running, even after selecting CAA record in advanced I am unable to get a valid test for CAA:

**Comment by Night1** [comment]
http://dnsviz.net/d/crt.cloud/dnssec/ 

Only A,NS, SOA, TXT and MX  shows up not CAA :/ I have set up CAA in Cloudflare
