### ISSUE TITLE
ImportError: No module named config

### ISSUE THREAD

**Issue by aabdnn** [dnsviz/dnsviz#21]
I've just installed dnsviz into a python virtualenv on my MacOSX laptop. Here's the list of installed modules:

```
$ pip list
Package    Version
---------- -------
appdirs    1.4.3  
dnspython  1.15.0 
dnsviz     0.6.5  
M2Crypto   0.26.0 
packaging  16.8   
pip        9.0.1  
pygraphviz 1.3.1  
pyparsing  2.2.0  
setuptools 34.3.3 
six        1.10.0 
typing     3.6.1  
wheel      0.29.0 
```

When I try to run any command, I get:

```
$ dnsviz probe
Traceback (most recent call last):
  File "/tmp/dnsviz/bin/dnsviz", line 92, in <module>
    main()
  File "/tmp/dnsviz/bin/dnsviz", line 74, in main
    mod = importlib.import_module('dnsviz.commands.%s' % command)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/dnsviz/lib/python2.7/site-packages/dnsviz/commands/probe.py", line 63, in <module>
    from dnsviz.analysis import WILDCARD_EXPLICIT_DELEGATION, PrivateAnalyst, PrivateRecursiveAnalyst, OnlineDomainNameAnalysis, NetworkConnectivityException, DNS_RAW_VERSION
  File "/tmp/dnsviz/lib/python2.7/site-packages/dnsviz/analysis/__init__.py", line 1, in <module>
    from .online import WILDCARD_EXPLICIT_DELEGATION, Analyst, OnlineDomainNameAnalysis, PrivateAnalyst, RecursiveAnalyst, PrivateRecursiveAnalyst, NetworkConnectivityException, DNS_RAW_VERSION
  File "/tmp/dnsviz/lib/python2.7/site-packages/dnsviz/analysis/online.py", line 50, in <module>
    import dnsviz.query as Q
  File "/tmp/dnsviz/lib/python2.7/site-packages/dnsviz/query.py", line 54, in <module>
    from .response import *
  File "/tmp/dnsviz/lib/python2.7/site-packages/dnsviz/response.py", line 54, in <module>
    from .util import tuple_to_dict
  File "/tmp/dnsviz/lib/python2.7/site-packages/dnsviz/util.py", line 37, in <module>
    from .config import DNSVIZ_SHARE_PATH
ImportError: No module named config
```

Looks like dnsviz is trying to load stuff from a module file called "config", but there's no such file in the dnsviz directory.

**Comment by cdeccio** [comment]
Hi Anand,

During the setuptools/distutils "install" command the file "config.py" is created from "config.py.in", using install-specific paths.  That must not be happening during your install.  What commands are you using to install in your virtual environment?

Casey

**Comment by aabdnn** [comment]
Hi Casey. I have built a wheel of dnsviz, with "pip wheel dnsviz". This downloads the tarball, unpacks it, and calls "python setup.py bdist_wheel". And indeed, config.py is not in the wheel.

**Comment by aabdnn** [comment]
I just had a look at config.py.in. It has some paths where dnsviz looks for some of its data. This design is probably imcompatible with wheels, which are typically built on one system, and installed somewhere else, somewhat like DEBs and RPMs.
Instead of a template that's expanded at installation, you probably need to make config.py contain a function that looks at sys.real_prefix and/or sys.prefix to determine if it's running in a virtualenv or somewhere else, and look for its data files relative to that. For example:

```
import sys

if hasattr(sys, 'real_prefix'):
    # in a virtualenv
    venv_dir = sys.prefix
```

**Comment by cdeccio** [comment]
@aabdnn Can you confirm that #31 fixes this for you?

Bonus points if you can show that it doesn't break packaging for anything else :)

**Comment by aabdnn** [comment]
Nope, sorry to disappoint you, but #31 doesn't fix the problem.

**Comment by cdeccio** [comment]
pypa/wheel/issues/92 (closed) seems to confirm the problem but indicates that there's nothing wrong with wheel, which puts the responsibility back on the developer :)

**Comment by aabdnn** [comment]
Hi Casey. They're right :) I also indicated to you in an earlier comment on 4th April how you could try to fix it. You didn't reply to that comment. Please look at it again.

**Comment by aabdnn** [comment]
Ok, thanks for letting me know. If I can help with any additional testing, please do reach out.

**Comment by cdeccio** [comment]
Please see if 7013d5a fixes this.

**Comment by cdeccio** [comment]
Just checking if this is no longer an issue, so I can close it out.  Trying to get things in order for 0.7.0 release.

**Comment by aabdnn** [comment]
Hi Casey,

I’m on holiday now so I can’t check. I can only look when I return on 4
Feb. However the last time I looked this issue was still not fixed.

Anand

**Comment by cdeccio** [comment]
> Hi Casey, I’m on holiday now so I can’t check. I can only look when I return on 4 Feb. However the last time I looked this issue was still not fixed. 

Just checking in...
