### ISSUE TITLE
0x20 testing

### ISSUE THREAD

**Issue by Habbie** [dnsviz/dnsviz#25]
PowerDNS auth 4.0.0-4.0.3 (fixed in 4.0.4) would mess up NSEC records for 0x20 (random casing) queries. We've had trouble getting people to upgrade because 'dnsviz is happy'. Could dnsviz perhaps (additionally?) randomise case in its queries to detect this failure? I'm pretty sure we're not the only one to have done broken things in this area.

**Comment by cdeccio** [comment]
Thanks... sorry about the happiness :)  Believe it or not, it's been on my list (though apparently no issue for it), and I have a path forward for it, but I just haven't had the cycles.
