### ISSUE TITLE
Please add support for algo 15+16

### ISSUE THREAD

**Issue by mdavids** [dnsviz/dnsviz#28]
Example domains:

ed25519.nl (algo 15)
dnssec-check.nl (algo 16)

**Comment by cdeccio** [comment]
Fixed with #67 .

**Comment by mnordhoff** [comment]
I don't think the live instance on https://dnsviz.net/ supports 16 yet, though? https://dnsviz.net/d/ed448.nl/dnssec/

(It supports 15!)

**Comment by cdeccio** [comment]
It's fixed in the code 375941d, but it has not yet been deployed at https://dnsviz.net/
