### ISSUE TITLE
test for non-compliance of Empty Non-Terminals

### ISSUE THREAD

**Issue by ogud** [dnsviz/dnsviz#34]
This only applies to zones that have "deep" labels like. _dns._tcp.example.com 

in this case _tcp is a empty non-terminal i.e. no records exist at it 
Right answer for _tcp.example.com is "empty answer"  
wrong answer includes Time-out, NXDomain, Refused, SERVFAIL 

sometimes hard to detect when there is a wild card so check with multiple RRtypes 
after support for the RRtype's has been established

**Comment by cdeccio** [comment]
I'm pretty sure this behavior is already implemented, i.e., evaluation of empty-nonterminals:

https://github.com/dnsviz/dnsviz/blob/master/dnsviz/analysis/offline.py#L1306

  Do you have any examples in which it's not doing what you think it should?

**Comment by cdeccio** [comment]
Also, I should mention that it also generally looks for other response errors (e.g., REFUSED, SERVFAIL, etc), in addition to the NXDOMAIN checks.

I'm going to close the issue, but if you see something that isn't handled by the current implementation, please feel free to comment and re-open, if necessary.
