### ISSUE TITLE
Find the ID 

### ISSUE THREAD

**Issue by Luis-Filipe** [dnsviz/dnsviz#37]
Hello folks,

I want to know if it´s possible to know the id, using the tool dnsviz, ex:

dnsviz probe example.com

From the gui interface the search: http://dnsviz.net/d/dnsviz.net/dnssec/ return a DNSKEY =id 28345.

Thanks in advance,
Luis

**Comment by cdeccio** [comment]
Hi Luis,

Try:

`dnsviz probe example.com | dnsviz print`

or:

`dnsviz query example.com`

The DNSKEY information is shown in abbreviated format: algorithm/keytag/flags.
