### ISSUE TITLE
Inaccurate display for KSK algorithm rollover

### ISSUE THREAD

**Issue by sebastianw** [dnsviz/dnsviz#41]
Hi, I did a KSK algorithm rollover for the zone 6v6.de. My DNS server (knot) does this automatically and follows [RFC6781 4.1.4 for KSK algorithm rollovers](https://tools.ietf.org/html/rfc6781.html#section-4.1.4). After the new KSK was introduced it looked like it only signed itself:
http://dnsviz.net/d/6v6.de/W9AmtA/dnssec/

When in reality the new KSK signed all DNSKEYs in the zone (as it should). This only became visible after the parent introduced the new algorithm DS:

http://dnsviz.net/d/6v6.de/W9Ar5Q/dnssec/

I would have expected that the signature from the new KSK over the whole DNSKEY set would be visible even before the DS change.

**Comment by cdeccio** [comment]
Hi Sebastian,

Here is a snippet from the dnsviz-graph man page:

> Just like other RRsets, a DNSKEY RRset is signed as an RRset, which comprises all the collective DNSKEY RRs at the zone apex.  Because each DNSKEY RR is represented as a node in DNSViz, a single RRSIG covering the DNSKEY RRset is represented  by  edges drawn from the node representing the signing DNSKEY to the nodes representing every DNSKEY RR in the set.
> 
> In  some  DNSSEC  implementations,  multiple DNSKEYs sign the DNSKEY RRset, even though only a subset are designated to provide secure entry into the zone (e.g., via matching DS records in the parent zone).  While there is nothing inherently wrong with this configuration, graphically representing such scenarios can be visually complex because of the cycles and redundancy created in the graph.
> 
> In order to represent trust propagation in a simplified fashion, eliminating graphic redundancies, DNSViz exhibits the following behavior.  For every DNSKEY signing the DNSKEY RRset, a self-directed edge is added to the node, indicating that the DNSKEY is self-signing.  Additionally, if the DNSKEY is designated as a (SEP) into the zone, then edges are drawn from its node to nodes representing all other DNSKEY RRs in the DNSKEY RRset.
> 
> If there is no true SEP, (e.g., no DS RRs in the parent zone), then SEP(s) are inferred based on their signing role (e.g., siging DNSKEY RRset or other RRsets) and properties (e.g., SEP bit).

To override this behavior in the Web interface, you select the "show redundant edges" option under "DNSSEC options", e.g.,:

http://dnsviz.net/d/6v6.de/W9AmtA/dnssec/?rr=all&a=all&ds=all&red=on&ta=.&tk=

Thanks,
Casey

**Comment by sebastianw** [comment]
Yeah, sorry about that. Somehow I did not realize that a self signature means the whole DNSKEY set is signed. Brain fart. :(

**Comment by cdeccio** [comment]
:)
