### ISSUE TITLE
Getting "Notices" simillar to dnsviz.net output.

### ISSUE THREAD

**Issue by jacekmigacz** [dnsviz/dnsviz#45]
I'm trying to fetch notices (warnings and errors) using installed locally dnsviz binary.
As an example: http://dnsviz.net/d/news.sabay.com.kh/dnssec/ it reports 2 errors and 6 warnings (2018-12-25 14:35:24 UTC).
I'm trying with:
$ dnsviz probe news.sabay.com.kh >news.sabay.com.kh.json
$ dnsviz grok <news.sabay.com.kh.json
How does it work. Am I missing something?

**Comment by cdeccio** [comment]
Try using `-A`, which indicates that you want to probe authoritative DNS servers:
```
dnsviz probe -A news.sabay.com.kh | dnsviz grok -lwarning
```
Some errors are server errors and some errors are content errors.  If you don't use `-A`, you won't see (authoritative) server errors because the recursive servers are used.

**Comment by jacekmigacz** [comment]
Thanks @cdeccio!
This is something, but I need to find out why is is failing on my machine...

> root@4446f54d5dfb:~# dnsviz probe -A news.sabay.com.kh
No global IPv6 connectivity detected
Error analyzing news.sabay.com.kh
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/commands/probe.py", line 146, in _analyze
    a = cls(name, rdclass=rdclass, dlv_domain=dlv_domain, try_ipv4=try_ipv4, try_ipv6=try_ipv6, client_ipv4=client_ipv4, client_ipv6=client_ipv6, query_class_mixin=query_class_mixin, ceiling=c, edns_diagnostics=edns_diagnostics, explicit_delegations=explicit_delegations, stop_at_explicit=stop_at_explicit, odd_ports=odd_ports, extra_rdtypes=extra_rdtypes, explicit_only=explicit_only, analysis_cache=cache, cache_level=cache_level, analysis_cache_lock=cache_lock, transport_manager=tm, th_factories=th_factories, resolver=resolver)
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/analysis/online.py", line 1080, in __init__
    self.local_ceiling = self._detect_ceiling(ceiling)[0]
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/analysis/online.py", line 1171, in _detect_ceiling
    ans = self.resolver.query_for_answer(ceiling, dns.rdatatype.NS, self.rdclass)
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/resolver.py", line 423, in query_for_answer
    response, server = self.query(qname, rdtype, rdclass)
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/resolver.py", line 411, in query
    l = self._query(qname, rdtype, rdclass, 0, self.SRC_NONAUTH_ANS)
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/resolver.py", line 564, in _query
    q.execute(tm=self._transport_manager, th_factories=self._th_factories)
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/query.py", line 1482, in _func
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/query.py", line 1492, in execute
    self.execute_queries(self, ignore_queryid=ignore_queryid, tm=tm, th_factories=th_factories)
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/query.py", line 1441, in execute_queries
    raise SourceAddressBindError('Unable to bind to local address (%s)' % (errno.errorcode[errno1]))
SourceAddressBindError: Unable to bind to local address (EADDRNOTAVAIL)

**Comment by cdeccio** [comment]
Curious.  Could you try running `dig +trace news.sabay.com.kh` from the same machine and see if that gives any errors?

**Comment by cdeccio** [comment]
Hmm.  You are receiving responses from 192.168.1.1 instead of from one of the root servers.  Something is wrong there.

**Comment by jacekmigacz** [comment]
I prepended G's nameserver to /etc/resolv.conf
```
nameserver 8.8.8.8
nameserver 192.168.1.1
```
Now dig +trace output is:

> root@4446f54d5dfb:/# dig +trace news.sabay.com.kh; echo $?
> 
> ; <<>> DiG 9.10.3-P4-Debian <<>> +trace news.sabay.com.kh
> ;; global options: +cmd
> .                       48697   IN      NS      e.root-servers.net.
> .                       48697   IN      NS      h.root-servers.net.
> .                       48697   IN      NS      l.root-servers.net.
> .                       48697   IN      NS      i.root-servers.net.
> .                       48697   IN      NS      a.root-servers.net.
> .                       48697   IN      NS      d.root-servers.net.
> .                       48697   IN      NS      c.root-servers.net.
> .                       48697   IN      NS      b.root-servers.net.
> .                       48697   IN      NS      j.root-servers.net.
> .                       48697   IN      NS      k.root-servers.net.
> .                       48697   IN      NS      g.root-servers.net.
> .                       48697   IN      NS      m.root-servers.net.
> .                       48697   IN      NS      f.root-servers.net.
> .                       48697   IN      RRSIG   NS 8 0 518400 20190116050000 20190103040000 16749 . HZAk2QhaVCMrzTrEfXg2xk1v96L3dMMOmDIMyZnC/zGLzjmqE2ICt+Pj cx3fJOretQEVWMpJH3ma6nrSZjeTrAiUH5+OT5e4qwJsd7ZGI7nV88R2 GZa8q2mDCGLn0A+4SQciycKGxZEU6AFU5h8N/tQfAIM5lNCx9ryfmo3A dEoW66IcA2HKk3QhxR0s6/xdIpwUNTfCr9MZGLP/lw00q4zvCseDO2HX 8ULn2N8yIQhPhwTCvc10r9vRjasRgiyfY2eFXLvzQ0XPnvB7b5P8Fxv+ w5iQMg980ezzpPkqvg760L2euT22lXBZrU1IfVkSrA5olRiosiAznmkr Y1xH2g==
> ;; Received 525 bytes from 8.8.8.8#53(8.8.8.8) in 25 ms
> 
> kh.                     172800  IN      NS      ns.camnet.com.kh.
> kh.                     172800  IN      NS      ns1.dns.net.kh.
> kh.                     172800  IN      NS      ns4.apnic.net.
> kh.                     172800  IN      NS      dns1.online.com.kh.
> kh.                     86400   IN      NSEC    ki. NS RRSIG NSEC
> kh.                     86400   IN      RRSIG   NSEC 8 1 86400 20190118170000 20190105160000 16749 . NlQiXlCuadTIMva21rRaQVfsovb9oDfTEjkbREhKb6G+7yzzTKsA0xyf vXetTX8WF/EDIftEt9efNs6eVP2fp1oEVOcgWEloU4FvGDyfYzc/kSur Zad4u1rrsy3lg1VqwqMM5BuCxmsjfrzTTADAUXjaQy7V+zio9c1gBOz0 fRpZ7uCrTclufrY3XJRTRFxE0P2ChchotX70HYv9CYU0pEUISElMsdmN 9MvXUw/noGCtDGfdlWqg2Ag/PxVhvymyvGPlogNW8JUz4HDZptt9/qqR EafHuOkGjRP6zTDigmLksepG+IIWULWc0NEojRseu16Xj+YPyHDTuhm2 AkkQ2A==
> ;; Received 552 bytes from 198.41.0.4#53(a.root-servers.net) in 29 ms
> 
> sabay.com.kh.           10800   IN      NS      ns2.sabay.com.kh.
> sabay.com.kh.           10800   IN      NS      ns1.sabay.com.kh.
> ;; Received 114 bytes from 203.223.32.3#53(ns.camnet.com.kh) in 614 ms
> 
> news.sabay.com.kh.      86400   IN      CNAME   cdn.sabay.com.
> cdn.sabay.com.          86400   IN      A       118.67.201.33
> cdn.sabay.com.          86400   IN      A       118.67.202.66
> sabay.com.              86400   IN      NS      ns02.sabay.com.
> sabay.com.              86400   IN      NS      ns01.sabay.com.
> ;; Received 231 bytes from 118.67.201.10#53(ns2.sabay.com.kh) in 400 ms
> 
> 0
> 
But still my dnsviz command fails for the same reason.

> SourceAddressBindError: Unable to bind to local address (EADDRNOTAVAIL)

**Comment by cdeccio** [comment]
Just for kicks, could you try checking out the `no_socket_bind` branch and see if it fixes your issue?

**Comment by jacekmigacz** [comment]
It didn't (ae941a26656d7131df95e8744aa038edd48f68e2).

**Comment by cdeccio** [comment]
Hmm.  I'm really sorry.  I don't know what else to check.

**Comment by cdeccio** [comment]
See the notes on the README.md under "Docker" to see if that helps.  In particular, see the section on setting up a host network.

**Comment by cdeccio** [comment]
Just noticed this is a duplicate of #32

**Comment by jacekmigacz** [comment]
@cdeccio that sort things out. Thanks!
