### ISSUE TITLE
probe: using -t may cause deadlock with Python3

### ISSUE THREAD

**Issue by tomaskrizek** [dnsviz/dnsviz#46]
## Description 
When using the `-t` options to run dnsviz probe in multiple threads, it seems some data can cause deadlock. As of 2019-01-14, the following query deadlocks:

```
$ time dnsviz probe -t 2 www.adhomepage.com > /dev/null
Analyzing www.adhomepage.com
Analyzing adhomepage.com
Analyzing com
Analyzing .
Analyzing hdredirect-lb5-1afb6e2973825a56.elb.us-east-1.amazonaws.com
Analyzing elb.us-east-1.amazonaws.com
Analyzing us-east-1.amazonaws.com
Analyzing amazonaws.com
^CInterrupted.

real    7m45.040s
user    0m0.861s
sys     0m0.117s
```

Interestingly enough, without the `-t` option, the domain is analyzed just fine.

```
$ time dnsviz probe www.adhomepage.com > /dev/null
Analyzing www.adhomepage.com
Analyzing adhomepage.com
Analyzing com
Analyzing .
Analyzing hdredirect-lb5-1afb6e2973825a56.elb.us-east-1.amazonaws.com
Analyzing elb.us-east-1.amazonaws.com
Analyzing us-east-1.amazonaws.com
Analyzing amazonaws.com

real    0m1.211s
user    0m0.528s
sys     0m0.061s
```

## Versions
- latest dnsviz - master (82aa568)
- python: 3.7.2
- dnspython: 1.16.0
- m2crypto: 0.30.1
- pygraphviz: 1.5

## Additional info
The probe command works fine when using dnsviz 0.6.7 and Python 2

**Comment by kimbo** [comment]
I'm guessing this can be closed. I ran that same command 100 times in 45 seconds.

```bash
time for i in {1..100}; do dnsviz probe -t 2 www.adhomepage.com; done >/dev/null
...

real	0m45.308s
user	0m29.421s
sys	0m6.753s

**Comment by tomaskrizek** [comment]
The issue still persists, I suppose it's just that particular domains was somehow fixed.

You can try with the files attached below, there are some domains that cause this behaviour.

```
dnsviz probe -f domains.txt -t 100  # won't finish
dnsviz probe -f domains.txt  # finishes, but it takes a while
```

[domains.txt](https://github.com/dnsviz/dnsviz/files/3467592/domains.txt)
[domains_new.txt](https://github.com/dnsviz/dnsviz/files/3467593/domains_new.txt)

**Comment by kimbo** [comment]
@tomaskrizek you're right. When you run it with just one thread, the domains that take forever just time out after a second or two, but with multiple threads it just sits there.
