### ISSUE TITLE
dnsviz grok crashing

### ISSUE THREAD

**Issue by army1349** [dnsviz/dnsviz#56]
**Version**: dnsviz 0.8.2 on FreeBSD
When I generate report like this:
`dnsviz probe -d 0 -o report.json -A example.com`
and then I try to analyze it like this:
`dnsviz grok -r report.json`
then this second step crashes for some reports every time and works for others.
Here is [traceback.zip](https://github.com/dnsviz/dnsviz/files/3664559/traceback.zip).
I can send failing report, if requested.

**Comment by cdeccio** [comment]
Can you provide a domain for which this error still occurs?

**Comment by army1349** [comment]
Yep, I can send you fresh report.json.
Can you give me a way to send it to you privately?

**Comment by cdeccio** [comment]
Email me at casey -at- deccio -dot- net and we'll work it out.

**Comment by cdeccio** [comment]
Can you try sending it as an attachment to: Dropbox.6nyjtm4fn5j1jgbz@u.box.com .  This will upload it to a private folder.

**Comment by army1349** [comment]
Thanks!
