### ISSUE TITLE
pygraphviz version check

### ISSUE THREAD

**Issue by wfms** [dnsviz/dnsviz#6]
On this system (Debian Wheezy 7), easy_install pulled in pygraphviz no problem, but upon trying to execute dnsviz, it seems the version checking might be a bit off:

pygraphviz version >= 1.1 is required, but version 1.3rc2 is installed.

**Comment by cdeccio** [comment]
Thanks for the report.  I'll fix it shortly.

As a side note, the wheezy version of pygraphviz is 1.1, so it can be
downloaded with apt-get install python-pygraphviz.
