### ISSUE TITLE
Backtrace when /etc/resolv.conf is missing

### ISSUE THREAD

**Issue by jayvdb** [dnsviz/dnsviz#61]
dnspython 2 needs /etc/resolv.conf , and openSUSE has ['eradicated'](https://kubic.opensuse.org/blog/2019-12-05-usr-etc/) that.  The result is rather odd here

```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dnsviz/commands/probe.py", line 153, in _analyze
    return a.analyze()
  File "/usr/lib/python3.8/site-packages/dnsviz/analysis/online.py", line 1513, in analyze
    return self._analyze(self.name)
  File "/usr/lib/python3.8/site-packages/dnsviz/analysis/online.py", line 2368, in _analyze
    self._analyze_name(name_obj)
  File "/usr/lib/python3.8/site-packages/dnsviz/analysis/online.py", line 2403, in _analyze_name
    servers = name_obj.zone.get_auth_or_designated_servers()
AttributeError: 'NoneType' object has no attribute 'get_auth_or_designated_servers'
```

Debugging it a bit

```py
$ ./bin/dnsviz probe example.com
Analyzing example.com
Error analyzing example.com
Traceback (most recent call last):
  File "/home/jayvdb/projects/dns/dnsviz/dnsviz/commands/probe.py", line 159, in _analyze
    return a.analyze()
  File "/home/jayvdb/projects/dns/dnsviz/dnsviz/analysis/online.py", line 1514, in analyze
    return self._analyze(self.name)
  File "/home/jayvdb/projects/dns/dnsviz/dnsviz/analysis/online.py", line 2374, in _analyze
    self._analyze_name(name_obj)
  File "/home/jayvdb/projects/dns/dnsviz/dnsviz/analysis/online.py", line 2409, in _analyze_name
    assert name_obj.zone, name_obj
AssertionError: example.com
```

And `is_zone()` is False, so `.zone` is `.parent` which is the `None` we see above.

When I move /usr/etc/resolv.conf to /etc/resolv.conf it magically works.

While this is probably a problem for dnspython to improve, very likely dnsviz can better detect that dnspython is broken and fail in a more user-friendly way.

**Comment by cdeccio** [comment]
Wow, thanks for that.  Admittedly, I had been warned of the dnspython 2 release, but never got around to testing it with DNSViz.  So here we are with potentially the first bug related to dnspython 2 :). There are already a number of fixes I've put added for dnspython behavior in previous versions.  I'll have to see what makes sense for this one.

**Comment by jayvdb** [comment]
Raised upstream https://github.com/rthalley/dnspython/issues/589

**Comment by cdeccio** [comment]
See also b329fcf.  As noted in c30437a:

A more flexible solution would allow the user to specify the
location of `resolv.conf` on the command line, but at least this gives the
user more explanation, and they have two options:
 - modify `setup.py` during build/installation, such that `RESOLV_CONF`
   points to the appropriate system-specific `resolv.conf`; or
 - install a symbolic link to the system-specific `resolv.conf` at
   `/etc/resolv.conf`.

**Comment by cdeccio** [comment]
> Raised upstream [rthalley/dnspython#589](https://github.com/rthalley/dnspython/issues/589)

Also, as far as I could tell, dnspython 2.0 was not actually the culprit.  This was just because `/etc/resolv.conf` was hard-coded (in multiple places) in DNSViz code.  Nonetheless, @jayvdb, if you could test it, that would be great.

**Comment by jayvdb** [comment]
If I just update master, I get:

```py
PYTHONPATH=${PWD} ./bin/dnsviz probe example.com
Traceback (most recent call last):
  File "./bin/dnsviz", line 108, in <module>
    main()
  File "./bin/dnsviz", line 90, in main
    mod = importlib.import_module('dnsviz.commands.%s' % command)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/jayvdb/projects/dns/dnsviz/dnsviz/commands/probe.py", line 66, in <module>
    from dnsviz.analysis import COOKIE_STANDIN, WILDCARD_EXPLICIT_DELEGATION, PrivateAnalyst, PrivateRecursiveAnalyst, OnlineDomainNameAnalysis, NetworkConnectivityException, DNS_RAW_VERSION
  File "/home/jayvdb/projects/dns/dnsviz/dnsviz/analysis/__init__.py", line 1, in <module>
    from .online import COOKIE_STANDIN, WILDCARD_EXPLICIT_DELEGATION, Analyst, OnlineDomainNameAnalysis, PrivateAnalyst, RecursiveAnalyst, PrivateRecursiveAnalyst, NetworkConnectivityException, DNS_RAW_VERSION
  File "/home/jayvdb/projects/dns/dnsviz/dnsviz/analysis/online.py", line 52, in <module>
    import dnsviz.resolver as Resolver
  File "/home/jayvdb/projects/dns/dnsviz/dnsviz/resolver.py", line 33, in <module>
    from .config import RESOLV_CONF
ImportError: cannot import name RESOLV_CONF
```
Obviously that isnt how you expect users to update the package, and I dont consider this a bug as a result, but it is a usecase you might like to consider.  It would be nice if config wasn't stored in `site-packages`.

After I update `dnsviz/config.py`, `dnsviz probe example.com` works.  Thank you!

The problem also exists upstream, which has a similar hard-coding.

**Comment by jayvdb** [comment]
Would you mind pinging me here when this is released, so I can update the openSUSE package and submit it into the main package collection
https://build.opensuse.org/package/show/home:jayvdb:py-new/dnsviz

**Comment by cdeccio** [comment]
> Obviously that isnt how you expect users to update the package, and I dont consider this a bug as a result, but it is a usecase you might like to consider.

Right.  I suppose that it's a one-time thing, and something that you would only expect in a development environment--as opposed to something you'd see if you had run `python setup.py build`.

> It would be nice if config wasn't stored in `site-packages`.

That could be changed, but that's definitely a bigger change and would require more cycles than I have at the moment to think about a better alternative.  In any case, this is one of the rare times when that file is changed on an existing install.

> 
> After I update `dnsviz/config.py`, `dnsviz probe example.com` works. Thank you!
> 

Okay - thanks for verifying.

> The problem also exists upstream, which has a similar hard-coding.

You're referring to dnspython?  I don't disagree - I'm just saying that the bug here had for a similar cause, but it was not _because_ of the dnspython issue.

**Comment by cdeccio** [comment]
> Would you mind pinging me here when this is released, so I can update the openSUSE package and submit it into the main package collection
> https://build.opensuse.org/package/show/home:jayvdb:py-new/dnsviz

I would be happy to, but could you open a dedicated issue for that?  Otherwise, I'll probably lose track of it :)

**Comment by cdeccio** [comment]
> Would you mind pinging me here when this is released, so I can update the openSUSE package and submit it into the main package collection
> https://build.opensuse.org/package/show/home:jayvdb:py-new/dnsviz

@jayvdb pinging

**Comment by jayvdb** [comment]
Thx.  Package updated.  Now running into all sorts of testing problems due to /etc/resolv.conf being empty, as testing VM is offline.  Need to run a fake nameserver and stuff it.  Or use https://github.com/jayvdb/dns-cache in a pytest plugin to intercept dnspython and use a pre-built dns cache.

**Comment by cdeccio** [comment]
Wait, I thought b329fcf fixed that. Can you not modify openSUSE's version of `setup.py`, so that it uses the correct `resolv.conf`?  Or are the saying the problem is something else?  Can you provide some examples, and open a new issue, if it makes sense?

**Comment by jayvdb** [comment]
This is a new problem, only relevant to packaging, where the tests need a mock DNS as the test VM is offline.  Will create new issues when I get a better understanding of the test suite.
