### ISSUE TITLE
warn about obsolete DNSSEC algorithms

### ISSUE THREAD

**Issue by pspacek** [dnsviz/dnsviz#63]
Just recently Fedora 33 has forbidden use of SHA1 for signature verification, which effectively [breaks DNSSEC on some domains](https://bugzilla.redhat.com/show_bug.cgi?id=1892704).

Besides this practical consequence, bunch of DNSSEC algorithms should not be use and I believe it would be beneficial to flag these as warnings. I propose to warn about algorithms involving MD5, SHA1, DSA, and GOST.

https://tools.ietf.org/html/rfc8624#section-3.1 and https://tools.ietf.org/html/rfc8624#section-3.2 give nice tables with not recommended or outright banned algorithms.

Unfortunately I'm not able to find head and tail in DNSViz code base so I'm not able to write patch, sorry and thank you for your time!

**Comment by cdeccio** [comment]
How would it be if it issued warnings or errors if the algorithm appeared alone for a given zone?  For example, if a zone has DS records for a given DNSKEY, with both digest types 1 and 2, then it doesn't warn/error.  But if it has only a DS record with type 1, then it is an error.  Does that sound reasonable?

**Comment by pspacek** [comment]
I think it would be more confusing than beneficial. E.g. if zone was signed with RSAMD5 and RSASHA256 at the same time, it would be a clear problem because RSAMD5 could allow signature forgery, effectively lowering (in)security down to RSAMD5 level, or in other words, false sense of security.

Does it make sense?

**Comment by cdeccio** [comment]
Fair enough.  For RRSIGs that is probably fine, but for DS records, that worries me because there are so many that use algorithm 1 in addition to algorithm 2, and validators are already required to ignore digest type 1 if digest type 2 is present.  In fact, I wonder why it (digest type 1) wasn't just made a MUST NOT validate.

**Comment by cdeccio** [comment]
@pspacek would you mind trying a few examples with the obsoletealg branch that I created?  Here is the gist of it:

- If a "MUST NOT validate" algorithm (DNSKEY or DS digest type) is used, it is ignored, unless special option (`-b`) is given on the command line.  In either case (with or without `-b`), a warning is issued.
- If a prohibited ("MUST NOT" sign) algorithm (DNSKEY or DS digest type) is used, a warning is issued.
- If an algorithm (DNSKEY or DS digest type) is used that is NOT RECOMMENDED, a warning is issued.  I don't currently have a way to override this.  Should I?

**Comment by cdeccio** [comment]
Also, and relatedly, should DNSViz always ignore digest type 2 if there is a stronger digest type in the same DS RRset?  At the moment, it only warns if there is a potential problem.

For example, suppose there are DS records corresponding to two DNSKEY records, A and B.

Scenario 1: DNSKEY A has DS records with both digest type 1 and digest type 2.  DNSKEY B has only a DS record with digest type 2.

Scenario 2: DNSKEY A has only a DS record with digest type 1.  DNSKEY B has only a DS record with digest type 2.

Currently, DNSViz warns only for scenario 2.

**Comment by wessels** [comment]
>     * If a "MUST NOT validate" algorithm (DNSKEY or DS digest type) is used, it is ignored, unless special option (`-b`) is given on the command line.  In either case (with or without `-b`), a warning is issued.
> 
>     * If a prohibited ("MUST NOT sign") algorithm (DNSKEY or DS digest type) is used, a warning is issued.
> 
>     * If an algorithm (DNSKEY or DS digest type) is used that is "NOT RECOMMENDED" for signing, a warning is issued.  I don't currently have a way to override this.  Should I?

I think that's pretty good.  My only quibble would be that MUST NOT sign and NOT RECOMMENDED sign algorithms are treated the same way (a warning), but of course you could differentiate them in the text of the warning message.

I know this is the repo for the command line tools, but I can't help but think about how you could maybe give the web UI user some options to accept/warn/fail on MUST NOT/NOT RECOMMENDED algorithms.

**Comment by cdeccio** [comment]
> My only quibble would be that MUST NOT sign and NOT RECOMMENDED sign algorithms are treated the same way (a warning), but of course you could differentiate them in the text of the warning message.

Thanks!  Good feedback.  That's actually how I ended up implementing these.

https://github.com/dnsviz/dnsviz/blob/obsoletealg/dnsviz/analysis/status.py#L230

> I know this is the repo for the command line tools, but I can't help but think about how you could maybe give the web UI user some options to accept/warn/fail on MUST NOT/NOT RECOMMENDED algorithms.

This could be done too.  There is a form already for the Web users, and I could add a couple more view/display options.

**Comment by cdeccio** [comment]
Fixed with #69
