### ISSUE TITLE
DNSVIZ don't enforce rfc5155#section-7.1 "Each empty non-terminal MUST have a corresponding NSEC3 RR"

### ISSUE THREAD

**Issue by kingcdavid** [dnsviz/dnsviz#64]
https://github.com/dnsviz/dnsviz/blob/master/dnsviz/analysis/status.py#L1250
https://github.com/dnsviz/dnsviz/blob/master/dnsviz/analysis/status.py#L1256

Here is looks like dnsviz checks the "Closest Encloser hash" is covered by the NSEC3, whereas i believe the RFC requires to check the  the label that is being requested in order to comply with https://tools.ietf.org/html/rfc5155#section-7.1

   o  Each empty non-terminal MUST have a corresponding NSEC3 RR, unless
      the empty non-terminal is only derived from an insecure delegation
      covered by an Opt-Out NSEC3 RR.

so for example

example.xx.yy

yy is a signed tld covered by an NSEC3 record
xx is a "empty non-terminal", so is not delegated (no ns records), so as per the rfc it requires an NSEC3 record, however in this example it doesn't have a NSEC

example.xx.yy is an unsigned delegation

Currently this scenario passes in dnsviz, however i think it is a false positive.

**Comment by cdeccio** [comment]
Thanks.  I'll take a look at this.  The NSEC(3) code hasn't been looked at in a while, and there are surely some corner cases that have been missed.  Do you have a specific example that you could supply here?

**Comment by kingcdavid** [comment]
Thanks for quick response! 

I do have a specific domain, but as I don't control it I'm hesitant to paste in here, is it possible to post privately?

**Comment by cdeccio** [comment]
You can send me an email at casey -at- deccio -dot- net

**Comment by kingcdavid** [comment]
After conversation with @cdeccio I've misunderstood the rfc, closing!
Thanks @cdeccio!
