### ISSUE TITLE
Recursive Resolver on different port

### ISSUE THREAD

**Issue by rithvikvibhu** [dnsviz/dnsviz#71]
I have a recursive resolver listening on `127.0.0.1:5350` that works with dig as expected:
```
$ dig @127.0.0.1 -p 5350 proofofconcept
;; QUESTION SECTION:
;proofofconcept.                        IN      A

;; ANSWER SECTION:
proofofconcept.         19466   IN      A       142.93.115.133

;; Query time: 95 msec
;; SERVER: 127.0.0.1#5350(127.0.0.1)
```

But when passing this to `dnsviz probe` with `-s`, it only uses `127.0.0.1:53` (the default port, not the one passed in arg).

For this to be tested, I've opened port 5350 on my VM and will keep it open for now.
```sh
# dig works as expected and returns A record
dig @40.113.229.250 -p 5350 proofofconcept

# dnsviz tries to access port 53 of that IP and fails
dnsviz probe -s 40.113.229.250:5350 proofofconcept
```

**Comment by rithvikvibhu** [comment]
After ~5 hours of trying to get bind9 to work (was trying to work around this in a different way), gave up and looked into the source.

Changed the port in dnsviz/query.py here and it worked.

Probably the port isn't being passed correctly to this function and is picking up the default argument 53:
https://github.com/dnsviz/dnsviz/blob/master/dnsviz/query.py#L1626

**Comment by cdeccio** [comment]
Sorry about that!  I tracked it down.  Fortunately, this was not a recent regression, like the last one #70 😄 .  Funny enough, looking at the code, I don't think this has _ever_ worked for recursive servers.  It _has_ worked for authoritative analysis though, which is the primary use case for DNSViz.  I guess you are the first one to attempt to use that functionality.  Anyway, I have a fix mostly in place and will get it pushed out soon.

**Comment by rithvikvibhu** [comment]
Haha good to know. Really appreciate the quick responses and fixes :)

Btw if you're curious, I'm using it for http://dnssec.rithvik (requires a handshake-aware resolver). The app queries a [Handshake](http://handshake.org/) node that's running alongside bind9 (and can't share port 53).

**Comment by cdeccio** [comment]
Cool - I'll check it out!
