### ISSUE TITLE
Feature request: qname min + aggressive use of DNSSEC validated cache

### ISSUE THREAD

**Issue by phonedph1** [dnsviz/dnsviz#76]
Some resolvers are now doing aggressive NSEC caching as well as qname minimization. This can easily expose issues where incorrect NSEC records are provided lower label depths.

For example `d.foo.bar.example.com` might have incorrect NSEC at `foo.bar.example.com` which covers `d`. Currently dnsviz will report no issues (same for the Verisign debugger).

It would be nice if these sorts of issues could be detected.

**Comment by cdeccio** [comment]
This has been implemented:

https://github.com/dnsviz/dnsviz/blob/master/dnsviz/analysis/errors.py#L978

If I'm not understanding what you are saying or if it is not working properly, please show me a counter example.

**Comment by cdeccio** [comment]
See also #68.

**Comment by marka63** [comment]
simplediagrams.com.	295	IN	NSEC	\000.simplediagrams.com. NS SOA MX TXT RRSIG NSEC DNSKEY CDS CDNSKEY TYPE30003

A records exist at simplediagrams.com but A missing from the type map it isn't detected.  In this case TLSA was the requested type. 

simplediagrams.com.	3600	IN	A	52.21.227.162
simplediagrams.com.	3600	IN	A	54.237.159.171
simplediagrams.com.	3600	IN	A	3.226.182.14
simplediagrams.com.	3600	IN	A	23.22.5.68

**Comment by pspacek** [comment]
It is detected, but not shown by default: https://dnsviz.net/d/simplediagrams.com/dnssec/?rr=all&a=all&ds=all&doe=on&ta=.&tk=

To show this breakage one needs to check this checkbox:
![screenshot](https://user-images.githubusercontent.com/11509590/144574716-541d89b5-49d5-4d6e-a778-8fefaca68484.png)

In other words, the only thing to be implemented is changing the default.

**Comment by marka63** [comment]
Then hopefully that can be done.

Unfortunately we all tend to focus on positive answers too much.  It's the negative answer implementations get wrong.

**Comment by cdeccio** [comment]
Fixed with https://github.com/dnsviz/dnsvizwww/commit/cf8820c9448278a36693a012ab5b5f47a0096981.  Will be updated on Web site soon.
