### ISSUE TITLE
No version information in JSON input: "0"

### ISSUE THREAD

**Issue by DragonLeo188** [dnsviz/dnsviz#80]
I have done the following steps

1) ```dnsviz probe -o example.com.json example.com```

Output: _example.com.json_

2) ```dnsviz grok -r example.com.json -t key_file -o example.com.123.json example.com```

Output: _example.com.123.json_

3) ```dnsviz graph -Thtml -r example.com.123.json -o example.com.123.html```

Output: _error_

I get the following message: **No version information in JSON input: "0"**

Can someone help me how to fix this ?

**Comment by cdeccio** [comment]
`dnsviz graph` takes in the output of `dnsviz probe` (i.e., `example.com.json`) not the output of `dnsviz grok` (i.e., `example.com.123.json`).
