### ISSUE TITLE
FR: Query and display NSEC3PARAM RR when analyzing a domain

### ISSUE THREAD

**Issue by puneetsood** [dnsviz/dnsviz#81]
The DNSSEC page for a domain at dnsvix.net shows the common records present at the start of a zone. Example: https://dnsviz.net/d/com/dnssec/

Given the industry effort to fix the use of NSEC3 parameters [1], it will be good to probe for and display NSEC3PARAM RR here.

[1] https://datatracker.ietf.org/doc/html/draft-hardaker-dnsop-nsec3-guidance

**Comment by cdeccio** [comment]
Thanks - that should be relatively easy.

**Comment by cdeccio** [comment]
I've committed the following: 26aa87  It hasn't made it to the Web site yet, but we'll move it there soon.

**Comment by cdeccio** [comment]
Okay, it's been deployed to https://dnsviz.net/.  One thing that remains is consistency checks between the NSEC3PARAM record and NSEC3 records.  But that will be for a different day and different issue.
