### ISSUE TITLE
EADDRNOTAVAIL on CentOS 8 with -A

### ISSUE THREAD

**Issue by quentinpraz** [dnsviz/dnsviz#84]
I'm trying to run the probe command with -A on a CentOS 8 and I am receiving the following error:

```
> sudo /usr/local/bin/dnsviz probe -A example.com
Error analyzing example.com
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dnsviz/commands/probe.py", line 165, in _analyze
[...]
  File "/usr/local/lib/python3.9/site-packages/dnsviz/query.py", line 1601, in execute
    self.execute_queries(self, ignore_queryid=ignore_queryid, tm=tm, th_factories=th_factories)
  File "/usr/local/lib/python3.9/site-packages/dnsviz/query.py", line 1550, in execute_queries
    raise SourceAddressBindError('Unable to bind to local address (%s)' % (errno.errorcode[errno1]))
dnsviz.query.SourceAddressBindError: Unable to bind to local address (EADDRNOTAVAIL)
```
I redeployed a new CentOS 8 from scratch and I'm still facing the same issue. I check the DNS settings (with dig) and I do not see any issue. I read the other issues related to this error (#45 & #32) but all of them are related to Docker. In my case, I'm running the command directly from the host.

Note that the probe command works without -A.

Thank you for your help.

_Host info:
Linux 4.18.0-240.22.1.el8_3.x86_64
CentOS Linux release 8.4.2105_

**Comment by quentinpraz** [comment]
I investigated further and it seems that the issue was related to IPv6. IPv6 was disabled on my CentOS8. However, even with the `--ipv4` parameter, IPv6 seems to be needed on CentOS8. I was able to solve the issue by enabling IPv6.

**Comment by cdeccio** [comment]
I've reproduced it and am working on a solution...

**Comment by cdeccio** [comment]
I think 44fc1f87 fixes this.  Please give it a try.

**Comment by quentinpraz** [comment]
Yes, it does fix the issue. Thank you for your fast reply!

**Comment by quentinpraz** [comment]
Do you plan to release a minor version following this fix? I'm installing your lib (with pip) in one of my project and it would be more convenient if the fixed version was available this way. Thank you

**Comment by cdeccio** [comment]
It took me a while, but 0.9.4 is now released.
