### ISSUE TITLE
Where does the build instal to ?

### ISSUE THREAD

**Issue by slchorne** [dnsviz/dnsviz#9]
I'm always wary of running any kind of 'sudo' without knowing what files it plans on touching.

yes, i could read the guts of the setup.py, but is there a summary of where all this will get placed when you run the install.

or - another way to ask the question: can dnsviz be run from the build folder without installing it ?
is there a way to test the the build worked without error ?

(If i try to run './bin/dnsviz probe' i get the error: 
`Traceback (most recent call last):
  File "./bin/dnsviz", line 80, in <module>
    main()
  File "./bin/dnsviz", line 58, in main
    import dnsviz.commands
`

**Comment by cdeccio** [comment]
See the output of:

`python setup.py install --help`

You can install to the user directory by doing the following (without sudo):

```
$ python setup.py build
$ python setup.py install --home=~/
```
Then you run something like this:

```
PYTHONPATH=~/lib/python/ ~/bin/dnsviz probe
```
Of course, it would be more convenient at this point to add ~/bin to PATH and ~/lib/python/ to PYTHONPATH in your .profile or equivalent.

Note that this user-directory-specific installation applies to other python packages built and installed with distutils--not just dnsviz.

**Comment by cdeccio** [comment]
And to answer your first question:

- the library files are installed in `$PREFIX/lib/python2.7/site-packages`
- the docs are installed in `$PREFIX/share/doc/dnsviz` and `$PREFIX/share/man/man1`
- the supporting data files are installed in `$PREFIX/share/dnsviz`

 ($PREFIX is usually `/usr` or `/usr/local`, but it all depends on the location of the python executable being used to perform the install)
