### ISSUE TITLE
Referrals from RFC 1034 servers for DS are not errors, warnings at best.

### ISSUE THREAD

**Issue by marka63** [dnsviz/dnsviz#95]
https://dnsviz.net/d/developer.apple.com/YaXcPQ/dnssec/

g.aaplimg.com to world-gen.g.aaplimg.com: The server(s) for the parent zone (g.aaplimg.com) responded with a referral instead of answering authoritatively for the DS RR type. (17.253.201.8, 17.253.206.8, UDP_-_EDNS0_4096_D_KN)

aaplimg.com is not signed and is hosted on a RFC 1034 server.

**Comment by cdeccio** [comment]
Mark, sorry for the late response.  I think what you are suggesting is that if the server is not hosting a signed zone, then the status can be softened?  I am okay with that.  There is some precedent for that in other areas of the code.
