### ISSUE TITLE
HTML-template require 'unsafe-inline' CSP

### ISSUE THREAD

**Issue by andreasschulze** [dnsviz/dnsviz#97]
The current HTML template contain [inline javascript](https://github.com/dnsviz/dnsviz/blob/9427a5c7d287664199315a2438b45521854a0c7d/share/html/dnssec-template.html#L14) code. If a webserver's administrator must use [content security policy declaration](https://content-security-policy.com/), this works only if one will include a policy "[script-src 'unsafe-inline'](https://content-security-policy.com/script-src/)"

_All_ javascript code must be moved to external files to avoid this unsafe setup.

**Comment by cdeccio** [comment]
Thanks for the issue, and sorry for the late response.

I'm not really sure how to fix this.  The idea was to have `dnsviz graph` produce a mostly self-contained HTML file that has an interactive graph.  The user can then load this into a Web browser to view it.  I see your point about CSP if that page generated by `dnsviz graph` is ever returned by a Web server, but that is out of scope.  If someone is building a Web server to return DNSViz results, then it will probably involve hacking parts of `dnsviz graph` to make it custom.  Does that make sense?  I really don't know how else I would fix it in DNSViz proper--at least not as a short-term fix.

**Comment by cdeccio** [comment]
Closing this for now.  If you can propose a way that this might be fixed given my considerations in the previous comment, I'm happy to reconsider.
